version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
        - .env
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

